# Generated by Django 4.2 on 2023-06-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0002_orderid_delete_message_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=4)),
                ('link', models.URLField()),
                ('status', models.BooleanField()),
                ('order_likes_id', models.CharField(max_length=8)),
                ('order_views_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderID',
        ),
    ]
